### ISSUE TITLE
active_admin.js loaded twice

### ISSUE THREAD

**Issue by exviva** [ejholmes/active_admin_editor#20]
Because `lib/active_admin/editor/engine.rb` calls `ActiveAdmin.setup`, which calls `Application#register_default_assets`, which unconditionally registers `active_admin.js`, I'm getting `active_admin.js` loaded twice on my page (first time it's registered in `config/initializers/active_admin.rb`).

I'm not sure if I should escalate it upstream to active admin, or if active admin editor should deal with it.

I'd be glad to provide a patch, if you have any suggestions @ejholmes .

Thanks for a great gem!

**Comment by ejholmes** [comment]
Odd, I would consider that a bug in active_admin itself (I think I ran across this before too). Maybe explicitly calling ActiveAdmin.application.register_x in the initializer would work better.

Thanks for the report!

**Comment by ejholmes** [comment]
This should be fixed in the latest version (1.0.5).

**Comment by exviva** [comment]
Wow, insane speed! Thanks!

**Comment by ejholmes** [comment]
:metal:

**Comment by freezepl** [comment]
hey,
i've updated gem to version 1.0.5 , and the problem still exists.. :(

EJ can You help?

**Comment by ejholmes** [comment]
@freezepl Did you upgrade from a 0.3.x version? Make sure you aren't including 'active_admin/editor' in your `app/assets/javascripts/active_admin.js` file. I should probably write an upgrade guide for 0.3.x -> 1.0.x ...

**Comment by jmajonis** [comment]
I was having this problem with 1.0.5, having upgraded from a previous version of this gem. Removing 'active_admin/editor' from app/assets/javascripts/active_admin.js worked for me.

**Comment by ejholmes** [comment]
Thanks for confirming. Closing this.
